### ISSUE TITLE
R CMD check NOTE re an extraneous dependency in Imports

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/data.adapt.multi.test#14]
When checking the pkg I see the following

> * checking dependencies in R code ... NOTE
> Namespace in Imports field not imported from: ‘SuperLearner’
>  All declared Imports should be used.

If you are not importing from **SuperLearner**, please remove it from the `Imports:` field in `DESCRIPTION`.

openjournals/joss-reviews/issues/161

**Comment by nhejazi** [comment]
We've not been able to replicate the problem stated in this issue locally. It's possible that it was fixed as a side-effect of recent changes. We'll continue trying and post updates as necessary.

**Comment by gavinsimpson** [comment]
@nhejazi Let me try to reproduce locally and if I can I'll post specific details of the check that I ran.

**Comment by gavinsimpson** [comment]
With the current master branch I still see (on Linux with R 3.4-0 patched):

```
$ R CMD check ./data.adapt.multi.test_0.2.0.tar.gz 
* using log directory ‘/home/gavin/work/git/data.adapt.multi.test.Rcheck’
* using R version 3.4.0 Patched (2017-04-22 r72596)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘data.adapt.multi.test/DESCRIPTION’ ... OK
* this is package ‘data.adapt.multi.test’ version ‘0.2.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘data.adapt.multi.test’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘SuperLearner’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... NONE
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
```

**Comment by gavinsimpson** [comment]
Interestingly, I don't see this if I do `R CMD check --as-cran`.

However, the problem is simple; you have `SuperLearner` in `Imports` (in `DESCRIPTION` in the master branch: https://github.com/wilsoncai1992/data.adapt.multi.test/blob/master/pkg/DESCRIPTION#L17) and yet you don't use this package anywhere (I grepped the R source to check) and don't use it in any `@importFrom` statements.

If you're not using this package in your package then just remove this line from `DESCRIPTION`. If you've already fixed this in the development branch (which I haven't checked) then you're good and this can be closed.

**Comment by nhejazi** [comment]
I've seen this problem come up in other packages I've worked on before, and yet I always forget exactly what the fix ends up being.

There is a problem with removing `SuperLearner` from `Imports` -- specifically, I think it gets re-added by `devtools::document` because `tmle::tmle` calls `SuperLearner::SuperLearner` internally.

It is rather odd that this seems to slip past `R CMD check --as-cran`.

I'll look into this further and report back if/when I am able to find a suitable fix.

**Comment by gavinsimpson** [comment]
What **tmle** does should be of no consequence for your package. You might want to ask if this is intended behaviour of `devtools::document()` as this is not what I would expect to happen nor what I understand the NAMESPACE rules to be.

This may be an issue in roxygen of course, as `document()` is just a wrapper to it.
